version: '2'
services:
    grocerybillingsystem-app:
        image: grocerybillingsystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://grocerybillingsystem-mysql:3306/grocerybillingsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    grocerybillingsystem-mysql:
        extends:
            file: mysql.yml
            service: grocerybillingsystem-mysql
